Numpy can be used to generate numbers (randomly generated numbers as well)

In [2]:
import numpy as np

arange()

In [3]:
arr=np.arange(0,10) #from 0 till 9 will be displayed having equal spaces of 1

In [4]:
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
arr_2=np.arange(0,20,step=2) #here the equal spaces will be of 2

In [10]:
print(arr_2)

[ 0  2  4  6  8 10 12 14 16 18]


linspace()

In [16]:
np.linspace(1,20,30) #here the total numbers that we will get in the given range is 60

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

Generating RANDOM numbers

random.rand() - gives floating point values as output


random.randint() - gives integer values as output

In [31]:
np.random.rand(3,4) #3 denotes number of rows and 4 denotes number of columns
#random.rand is going to give values between 0-1 (0-1 is the default range which cannot be changed)
#output will always be floating point numbers

array([[0.30230972, 0.71118035, 0.63119232, 0.81925524],
       [0.68242373, 0.90324033, 0.38963587, 0.19796472],
       [0.32924576, 0.54746712, 0.8945494 , 0.09953194]])

In [32]:
np.random.randint(3,20,6) #6 integer numbers will be displayed between 3-20
#here the range needs to be given by the user
#output will always be integer numbers 

array([14,  5,  7, 19, 14, 19])